on:
  push:
    branches:
      - main

concurrency:
  group: openfn-deployment
  cancel-in-progress: false

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.OPENFN_75b5159b_0102_4005_9fb7_2afa1693912e_API_KEY }}
          config_path_input: 'openfn-75b5159b-0102-4005-9fb7-2afa1693912e-config.json'
